### ISSUE TITLE
New name for program

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/awakened-poe2-trade2#7]
Original program creator requested a more different name for the poe2 version, [1507](https://github.com/SnosMe/awakened-poe-trade/issues/1507#issuecomment-2531539643_).

**Comment by sauerstein** [comment]
- Exalted Poe Trade
- Exiled Poe Trade
- Path of Merchant

That's what comes to my mind after a minute.

**Comment by timneve** [comment]
Trade of Exile

**Comment by Xebtria** [comment]
Persistent PoE Trade
you know, because auras n stuff now have the persistent tag, which is new in poe2, didn't exist in poe1.
also some sort of analogy to how the community is persistent enough to not let a program that fundamental to the game die.

**Comment by Frajmando** [comment]
I do like the idea of exalted poe trade, but my own suggestion would be

- Ascended PoE Trade

**Comment by spokeswamp** [comment]
"Quicksilver Trade" or something like that

**Comment by Juventinos** [comment]
I think "Artificer's PoE Trade" is a good name based on Artificer's Orb

**Comment by Kvan7** [comment]
Thank you all for your ideas!
For right now I think I am going to go with "Exile's Exchange"

**Comment by Juventinos** [comment]
I like that name and idea to remove poe trade, but still i belive it's better to go for something new and specific to poe 2 like Artificers Exchange.

But I think it's close so let's go!!!!

**Comment by Quantisaveri** [comment]
Personally, I think the best answer is Awakened PoE 2 Trade. But since the creator doesn't want that, here are a few goodies.

PoE 2 Trade Tool. 
Woke PoE 2 Trade
or my personal favorite, PoET. 

On a serious note, the original dev could have changed a few lines of code and released it as a separate program. Let's worry less about the name and worry more about getting it functional and available.
